name: Auto Update time.json

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Update time.json
        run: |
          TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "{ \"currentTime\": \"$TIME\" }" > time.json

      - name: Commit and push
        run: |
          git config user.name "TimeBot"
          git config user.email "sur2rock@example.com"
          git add time.json
          git commit -m "Update time.json: $TIME" || echo "No changes"
          git push
